### ISSUE TITLE
Sass 1.65 introduces breaking changes to this library

### ISSUE THREAD

**Issue by andyj89** [bbc/gel-sass-tools#13]
Since Sass 1.65, https://sass-lang.com/documentation/breaking-changes/calc-functions/ functions like `rem()` are parsed as CSS calculations. I think [this function](https://github.com/bbc/gel-sass-tools/blob/30e5dba15400ab77258e542e2d9dcbc5569f152e/lib/tools/_rem.scss#L29) can no longer be called
```css
@function rem($value, $baseline: $gel-base-font-size) {
```
I'm not a SASS expert but I think renaming it to something else might be a potential fix?

Just wondering if it's possible to test this library too?

**Comment by nicholasgriffintn** [comment]
Yup, just found this after upgrading, go this error:

```
Error: 2 arguments required, but only 1 was passed.
--
396 | ╷
397 | 73 │         #{$property}: rem($value);
398 | │                       ^^^^^^^^^^^

```

**Comment by randombitsUK** [comment]
This should now have been addressed in the latest major version. The other related repositories have also been updated.

There is still some work to do for SASS 2.0, but that will be done separately.

**Comment by randombitsUK** [comment]
No issues have been identified since the release so I'm assuming this is now resolved.

**Comment by randombitsUK** [comment]
No issues have been identified since the release so I'm assuming this is now resolved.
