### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by lukejpreston** [bbc/gel-sass-tools#6]
Could you publish this to NPM please?

**Comment by lukejpreston** [comment]
It is on version 1.1.0 and this is on 1.2.0

**Comment by randombitsUK** [comment]
This version was published to NPM (4 years ago!), as have the versions since.

**Comment by lukejpreston** [comment]
Haha, thanks! I left the BBC 4 years ago as well! But it is good to see progress is still being made on GEL :D
